services:
  - name: SDX Transformer
    id: sdx_transformer
    description: Transforms survey data
    health_check_url: http://localhost:5001/health
    version_url: http://localhost:5001/version

  - name: SDX Survey
    id: sdx_survey
    description: Another sdx microservice bruh
    health_check_url: http://localhost:5002/health
    version_url: http://localhost:5002/version
