services:
  - name: SDX Transformer
    description: Transforms survey data
    repo_url: http://github.com/sdx-transformer
    health_check_url: http://example.come/health

  - name: SDX Survey
    description: Another sdx microservice bruh
    repo_url: http://github.com/sdx-survey
    health_check_url: http://example.come/health

